### ISSUE TITLE
建议加入高DPI缩放支持

### ISSUE THREAD

**Issue by aTerminal** [skydevil88/XboxDownload#1]
现在的软件在高DPI显示下会出现模糊的情况，可以考虑把Forms改成DPI显示模式以提升视觉效果。
（高分辨率显示支持）

**Comment by skydevil88** [comment]
在我的LG 32UL950里没看出有区别，暂时只改了主页面。

**Comment by aTerminal** [comment]
https://blog.csdn.net/ffx54611/article/details/103530282
可以参考这篇文章，经过测试有效
![image](https://user-images.githubusercontent.com/47311923/122050997-af43f180-ce16-11eb-8aa0-b6c7fd87d11c.png)
![image](https://user-images.githubusercontent.com/47311923/122051091-c551b200-ce16-11eb-9469-a84d22a31400.png)

**Comment by skydevil88** [comment]
已加。
