### ISSUE TITLE
大部分游戏已经无法获取链接

### ISSUE THREAD

**Issue by steamch** [skydevil88/XboxDownload#10]
宽带：电信
系统：win10
下载：win10商店
今天测试了一下想要下的游戏均无法获取链接

**Comment by skydevil88** [comment]
七月份开始微软陆续更新数据，API已经不再发送下载链接，现在只能自己监听。

**Comment by steamch** [comment]
> 七月份开始微软陆续更新数据，API已经不再发送下载链接，现在只能自己监听。

但是现在奇怪的地方在于今天我监听也监听不到地址了[https://imgur.com/EqR5PqH](url)

**Comment by steamch** [comment]
> win10商店很多游戏使用应用下载域名，你把cn跟应用IP都指定到本机IP，然后再开始下载游戏，看到有 HTTP 404 日志就是下载地址。

[https://imgur.com/bTuQiQl](url)尝试了一下，指定到本机IP依然不行，没有日志输出。

**Comment by skydevil88** [comment]
> > win10商店很多游戏使用应用下载域名，你把cn跟应用IP都指定到本机IP，然后再开始下载游戏，看到有 HTTP 404 日志就是下载地址。
> 
> [https://imgur.com/bTuQiQl](url)尝试了一下，指定到本机IP依然不行，没有日志输出。

暂停下载重启PC吧，或者把下载任务删除，启动监听后再开始下载。

**Comment by steamch** [comment]
> > > win10商店很多游戏使用应用下载域名，你把cn跟应用IP都指定到本机IP，然后再开始下载游戏，看到有 HTTP 404 日志就是下载地址。
> > 
> > 
> > [https://imgur.com/bTuQiQl](url)尝试了一下，指定到本机IP依然不行，没有日志输出。
> 
> 暂停下载重启PC吧，或者把下载任务删除，启动监听后再开始下载。

重启之后可以了，谢谢解答
