### ISSUE TITLE
应用安装目录一直显示离线 修复也无效

### ISSUE THREAD

**Issue by Babyblue-BB** [skydevil88/XboxDownload#101]
![bfcea280ae12f996714a67a1b43e9b3e](https://github.com/user-attachments/assets/92828d15-9022-46e8-a1c2-c6b00645040d)
应用安装目录显示离线 尝试修复也不行 其他盘都正常 只有E盘显示离线 只有E盘空间足够安装游戏 该如何操作？

**Comment by skydevil88** [comment]
在Xbox app里设置看看，如果不能修改就在系统设置里改。
https://www.bilibili.com/video/BV1Bj411P7uE 
45秒有修改方法。

**Comment by skydevil88** [comment]
以管理员身份运行 PowerShell 
Set-AppxVolume -Volume E: -Online

**Comment by Babyblue-BB** [comment]
没啥问题，错误了也可以正常安装
