### ISSUE TITLE
游戏安装失败

### ISSUE THREAD

**Issue by Babyblue-BB** [skydevil88/XboxDownload#102]
Add-AppxPackage : 部署失败，原因是 HRESULT: 0x80073CF9, 无法安装。请联系你的软件供应商。 (异常来自 HRESULT:0x80073CF9)
MsixvcStagingSession 中的 Common::Deployment::MsixvcStagingSession::StagePackage 失败，出现错误 0x87E00010。
注意: 有关其他信息，请在事件日志中查找 [ActivityId] af296f85-df40-0004-bedc-29af40dfda01，或使用命令行 Get-AppPackageLog -ActivityID af296f85-df40-0004-bedc-29af40dfda01_x64_ww_5bkah9njm3e9所在位置 行:1 字符: 1                                                                                                                                                          [             + Add-AppxPackage -Path 'E:\下载\38985CA0.COREBase_1.0.16.0_x64_ww_5bkah9 ...                                                                                                                + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                                                                                                                          + CategoryInfo          : WriteError: (E:\下载\38985CA0....9njm3e9g.msixvc:String) [Add-AppxPackage], IOException                                                                            + FullyQualifiedErrorId : DeploymentError,Microsoft.Windows.Appx.PackageManager.Commands.AddAppxPackageCommand
 
麻烦看看怎么解决？200g下了一天才下好，安装不上

**Comment by skydevil88** [comment]
重启电脑或者重装游戏服务试试。

**Comment by skydevil88** [comment]
安装包放到根目录下，有中文路径也可能出错。

**Comment by Babyblue-BB** [comment]
也解决了，应该是下载的文件出错了，应该是数据有损坏，下载地区选错成tw了不知道有没有影响，又挂机重下了一晚上港版的，这次能正常安装游玩了
