### ISSUE TITLE
应用下载问题

### ISSUE THREAD

**Issue by ailinician** [skydevil88/XboxDownload#104]
选择的IP均出现The remote certificate was rejected by the provided RemoteCertificateValidationCallback.

**Comment by skydevil88** [comment]
可以试试用 Akamai IP.

**Comment by ailinician** [comment]
试了一些不同地区的Akamai IP也是The remote certificate was rejected by the provided RemoteCertificateValidationCallback.

**Comment by skydevil88** [comment]
下载地址使用 http, 浏览器会自动改为 https，需要手动改回来国。

**Comment by ailinician** [comment]
![屏幕截图 2024-09-27 140221](https://github.com/user-attachments/assets/ae62ec23-3c50-4560-9279-54b5ef19d4b0)
![屏幕截图 2024-09-27 135610](https://github.com/user-attachments/assets/cc217eca-a81f-44a3-a01b-60f028be2b0f)
麻烦了
主机下载应用时一直卡在开始下载，但是没有进度条

**Comment by skydevil88** [comment]
下载域名不使用HTTPS，不需要检测。
没法开始下载是因为 fe3cr.delivery.mp.microsoft.com 这个域名被SNI干扰/阻断了，这个域名是用来取回应用下载链接，只能等这个域名能够正常访问才会下载，或者开加速器梯子。

**Comment by ailinician** [comment]
感谢大佬解答
