### ISSUE TITLE
过时的链接/packages.xboxlive.com 身份验证令牌

### ISSUE THREAD

**Issue by cowboy-1337** [skydevil88/XboxDownload#106]
您好，我注意到您网站上的一些 Xbox 软件包已过时。我怎样才能自己得到它们？如何在packages.xboxlive.com/GetBasePackage 上验证自己的身份？ 请告知，谢谢！

**Comment by skydevil88** [comment]
https://github.com/skydevil88/XboxDownload-EN/blob/2aa9794ead48c85057356c43c336372e8255bcbc/XboxDownload/HttpsListen.cs#L185

**Comment by cowboy-1337** [comment]
看来我所要做的就是将请求定向到“packagespc”而不是具有相同标记的“packages”。

感谢您的帮助！ :)
