### ISSUE TITLE
【建议】希望能够在Release里面的assets文件增加版本号

### ISSUE THREAD

**Issue by Ban404** [skydevil88/XboxDownload#108]
感谢开发者，希望能够在Release里面的assets文件增加版本号，提高版本管理和文件追踪的效率。有助于确保下载的是正确的版本，并且可以方便地回溯和管理不同版本之间的差异。

**Comment by skydevil88** [comment]
目前软件自动更新需要匹配文件名，加上版本号就不能自动更新了。
