### ISSUE TITLE
PC下载，硬盘回传相关问题

### ISSUE THREAD

**Issue by Mrfireos** [skydevil88/XboxDownload#112]
![image](https://github.com/user-attachments/assets/0948f04d-7c28-429b-9df9-c7641ac5ca76)
![image](https://github.com/user-attachments/assets/7c05b60b-a7ce-4e7a-bb7b-9bcde688203c)
作者大大你好。
如图所示，xss本地下载游戏大小是80Gb，PC上的版本是130GB，应该是xsx的版本，
如果利用外置硬盘回传的话xss会产生额外的硬盘消耗，请问这个问题能解决吗？

**Comment by skydevil88** [comment]
PC下载的是完整安装包（可能包括4K、2K材质包），回传主机系统只会安装自身需要部分，不会额外占用硬盘空间。

**Comment by Mrfireos** [comment]
> 安装（可能包括4K、2K材质包），回传主机系统

好的，谢谢。我看软件上要求“游戏下载到移动硬盘后需要转到另一块再打开“，之后不需要的额外文件会自动清理吗？
这样的话就不用担心了，xss容量比较小

**Comment by skydevil88** [comment]
转移到另一块硬盘等同执行安装。
