### ISSUE TITLE
无法监听游戏下载地址

### ISSUE THREAD

**Issue by Benderay** [skydevil88/XboxDownload#12]
开启监听后在下载助手日志中没有游戏下载链接出现。

我的设置步骤：
1. 电脑与xss在同一无线局域网中，设置xss中DNS为电脑IP
2. 在下载助手中的"指定com下载域名IP"，"指定cn下载域名IP"处填写本机IP；"监听IP"处选"本机IP"
3. 已勾选项：跳转cn下载，启用DNS服务，启用HTTP服务，指定CDN Akamai，跳转CDN Akamai，启用本地上传
4. 点击"开始监听"
5. 在xss主机中选择游戏下载

监听日志中仅有"请求"项中出现"DNS 查询"；"内容"，"客户端IP"，"时间"均显示正常

**Comment by skydevil88** [comment]
有没有看到那几个下载域名DNS查询日志？有可能是DNS缓存问题，重启Xbox就能解决。
部分游戏会用应用下载域名（PC上面比较多，Xbox目前已知“我的世界”），这种情况可以把应用下载域名也指定为本机IP.

**Comment by Benderay** [comment]
> 有没有看到那几个下载域名DNS查询日志？有可能是DNS缓存问题，重启Xbox就能解决。 部分游戏会用应用下载域名（PC上面比较多，Xbox目前已知“我的世界”），这种情况可以把应用下载域名也指定为本机IP.

谢谢作者对项目的维护！

**Comment by Benderay** [comment]
> 有没有看到那几个下载域名DNS查询日志？有可能是DNS缓存问题，重启Xbox就能解决。 部分游戏会用应用下载域名（PC上面比较多，Xbox目前已知“我的世界”），这种情况可以把应用下载域名也指定为本机IP.

谢谢作者对项目的维护！具体域名忘记了，模糊的想起有查询下载地址asset1.xbox.cn的查询日志。我下次重启Xbox试试！
