### ISSUE TITLE
希望可以提供V6测速支持

### ISSUE THREAD

**Issue by zhxch3** [skydevil88/XboxDownload#13]
希望可以提供V6地址测速支持，现在手动导入v6依旧不可用

**Comment by skydevil88** [comment]
我家没有IPv6，有条件再看看。Xbox不能自定义v6 DNS，用处也不是很大。

**Comment by zhxch3** [comment]
谢谢了，因为是直接写入到路由里面劫持了，有时候写入了v4他还会自动解析V6地址出来

**Comment by skydevil88** [comment]
可以在防火墙中自定义规则，禁止Xbox使用IPv6

ip6tables -I INPUT -p icmpv6 -m mac --mac-source XBOX_MAC -j DROP 
ip6tables -I INPUT -p udp -m mac --mac-source XBOX_MAC --dport 547 -j DROP
