### ISSUE TITLE
如何获得国行游戏的下载地址？

### ISSUE THREAD

**Issue by hezlog** [skydevil88/XboxDownload#14]
在游戏》国服独占中文游戏选择国行游戏后，大部分游戏都不显示下载地址，请教这些下载地址如何收集？

**Comment by skydevil88** [comment]
现在API已经不发送下载地址，不过我还有备份
https://github.com/skydevil88/XboxDownload/blob/master/XboxDownload/FormChinese.cs

**Comment by hezlog** [comment]
非常感谢！
