### ISSUE TITLE
无法获取下载链接

### ISSUE THREAD

**Issue by tardlk** [skydevil88/XboxDownload#15]
下载网盘11.5日版本，使用后无法获取xbox及微软商店版下载链接
![image](https://user-images.githubusercontent.com/37508088/140557955-81bee3bb-e6b4-4f96-901a-2050eea113bf.png)
![image](https://user-images.githubusercontent.com/37508088/140557970-2b05358d-11f8-49f9-a7c0-df622eb029c8.png)

**Comment by skydevil88** [comment]
方法已经失效，下载链接自已监听。
