### ISSUE TITLE
修改系统Hosts文件失败。错误信息：尝试执行未经授权的操作

### ISSUE THREAD

**Issue by yuppiesnotzhuhao** [skydevil88/XboxDownload#16]
请问出现了这个错误要怎么解决呢？已经是管理员身份运行了

**Comment by skydevil88** [comment]
关闭杀毒软件，电脑管家之类软件。

**Comment by yuppiesnotzhuhao** [comment]
> 关闭杀毒软件，电脑管家之类软件。

多谢，但是我遇到一个问题，下载地平线5，点击开始下载后，过两分钟下载任务就消失了，助手里也没有日志

**Comment by skydevil88** [comment]
> > 关闭杀毒软件，电脑管家之类软件。
> 
> 多谢，但是我遇到一个问题，下载地平线5，点击开始下载后，过两分钟下载任务就消失了，助手里也没有日志

服务器问题，稍候再试就可以。
