### ISSUE TITLE
openwrt旁路由下设置失败

### ISSUE THREAD

**Issue by lfl8180232** [skydevil88/XboxDownload#19]
我是爱快+openwrt的使用环境，按照教程nginx的方法，主机名我这里设置为openwrt的ip地址，测试时笔记本网关指向op，测试assets1.xboxlive.com/1234没有跳转
补充：在op里ping assets1.xboxlive.com返回的是op地址，ping assets1.xboxlive.cn返回主机名里我测速的ip
请教

**Comment by skydevil88** [comment]
可以试试用Lighttpd，https://www.bilibili.com/video/BV1wP4y1G7zf

**Comment by lfl8180232** [comment]
我是从视频过来的，现在两个方法都同时用了，在op重启了n次之后突然就可以了，电脑访问跳转成功，不过ping cn的网址返回的不是我选的ip，不知道是不是smartdns这种在搞鬼
