### ISSUE TITLE
PC离线下载再网络回传给 Xbox 也会出现安装停止

### ISSUE THREAD

**Issue by BDZNH** [skydevil88/XboxDownload#20]
如题，遇到这种情况大佬有什么排查方向吗

**Comment by skydevil88** [comment]
最近国内CDN问题太多，里面的文件就是损坏的，先用本地上传，到了出错位置改用国外IP下载这一小段(.com .cn都指定到这个IP)，从国外下载出错部分，等过了出错数据再改回本地上传。

**Comment by BDZNH** [comment]
多谢解答
