### ISSUE TITLE
最近xbox国内网络出问题了吗？openwrt上面的加速方法没用了呢

### ISSUE THREAD

**Issue by justxiami** [skydevil88/XboxDownload#21]
之前openwrt设置成功之后，可以满速300m下载，
现在通过xbox下载助手测得的ip，换到openwrt的主机名之后
前面几秒能满速，然后马上断崖下跌，直接跌到没有速度
然后过个1-2分钟左右，从没有速度到500kbps，再重新涨到150m，然后继续跌回没速度
反反复复循环这样的情况

物理网线和路由方面应该没问题，uu加速就能一直卡死在30m，手机测速能300m满速

**Comment by skydevil88** [comment]
最近国内CDN服务器出了问题，很多文件损坏，暂时可以先用以下几个国外节点，包括 .cn 域名也指定到国外。

assets1.xboxlive.com
223.119.50.144	(中国香港 移动)	53|64|26.81
23.219.39.75	(日本东京都东京)	54|64|21.25
23.15.14.40	(日本东京都东京)	53|56|17.18
23.216.12.104	(日本大阪府大阪)	54|64|14.07
23.78.140.82	(日本大阪府大阪)	54|70|12.67
23.59.247.80	(日本东京都东京)	53|59|11.78

![image](http://tiebapic.baidu.com/forum/pic/item/d9ade839b6003af3dd0cecb0702ac65c1138b62f.jpg)

**Comment by WeirdFishBK201** [comment]
国内的玩家太难了
