### ISSUE TITLE
xbox貌似无法下载双人成行，总是下载到12.76G时候停止，会是网络问题吗？

### ISSUE THREAD

**Issue by Glenffi** [skydevil88/XboxDownload#22]
如图，我自己是在openwrt软路由上设置了eaplay的域名挟持
![1](https://user-images.githubusercontent.com/56630896/147200237-d2a7f900-d8a5-46cf-9908-f836adf87b30.jpg)

**Comment by skydevil88** [comment]
最近国内CDN服务器出了问题，解决方法 https://github.com/skydevil88/XboxDownload/issues/21
