### ISSUE TITLE
请问您的这种方法可否用于pc给Xbox共享网络，来用于给Xbox翻墙呢？

### ISSUE THREAD

**Issue by Looong01** [skydevil88/XboxDownload#23]
大佬你好，请问您的这种方法可否用于pc给Xbox共享网络，来用于给Xbox翻墙呢？因为是校园网的原因，无法给路由器刷插件，能想到的只有类似Xbox下载助手和游戏加速器的那种共享网络了。所以想问一下这么做可不可以？
我pc用的是clash，可以开启TUN全局模式，请问接下来给怎么做才能把网络共享给Xbox呢？系统是Windows 11 pro
或者有什么教程吗？

**Comment by skydevil88** [comment]
开代理热点 https://zhuanlan.zhihu.com/p/337430556

**Comment by skydevil88** [comment]
Xbox不支持Proxy设置，不能使用这类软件，校园网如果不能使用二级路由那也没办法。

**Comment by Looong01** [comment]
网上查到了这种方法，您觉得能实现吗？谢谢您！https://nga.178.com/read.php?tid=27706069&rand=62
![image](https://user-images.githubusercontent.com/69568351/147755317-b46909ac-0a78-4127-8869-0c3cd9ed8f6b.png)

**Comment by Looong01** [comment]
> Xbox不支持Proxy设置，不能使用这类软件，校园网如果不能使用二级路由那也没办法。
网上查到了这种方法，您觉得能实现吗？谢谢您！https://nga.178.com/read.php?tid=27706069&rand=62
![image](https://user-images.githubusercontent.com/69568351/147755317-b46909ac-0a78-4127-8869-0c3cd9ed8f6b.png)

**Comment by skydevil88** [comment]
Clash支持添加虚拟网卡，把加虚拟网卡共享出来应该行。

**Comment by Looong01** [comment]
> Clash支持添加虚拟网卡，把加虚拟网卡共享出来应该行。

请问如何共享虚拟网卡呢？是桥接连上的实际的wlan和虚拟tap网卡，组成网桥吗？

**Comment by skydevil88** [comment]
电脑双网卡，有线无线都可以，一个网口连接上网，另一个网口连接Xbox，开网络共享选择共享虚拟网卡。
单网卡没试过不清楚。

**Comment by roadwide** [comment]
https://github.com/zhxie/pcap2socks-gui
可以用这个

**Comment by Looong01** [comment]
> 共享虚拟网卡

兄弟可以出一个视频教程吗？没搞懂源设备和代理服务器都代表着什么[捂脸]。。。源设备是指Xbox，代理服务器是指我在电脑上clash上开启的vpn吗？如果是这样的话，Xbox上的DNS还是默认的吗？

**Comment by Looong01** [comment]
> 电脑双网卡，有线无线都可以，一个网口连接上网，另一个网口连接Xbox，开网络共享选择共享虚拟网卡。 单网卡没试过不清楚。

大佬说的共享操作在Windows上具体是怎么操作的呢？互联网协议的理论我倒是学过一些，但是Windows上的具体操作和应用我是真的完全不了解了[捂脸]

**Comment by Looong01** [comment]
> 电脑双网卡，有线无线都可以，一个网口连接上网，另一个网口连接Xbox，开网络共享选择共享虚拟网卡。 单网卡没试过不清楚。

如果方便的话可以出一个视频吗？

**Comment by skydevil88** [comment]
> 
双网卡共享上网 https://jingyan.baidu.com/article/e75aca8511695a142edac6d4.html ，操作应该差不多， 右键选择 Clash虚拟网卡，然后共享给连接 Xbox 的网卡。
