### ISSUE TITLE
感谢大佬，未来会不会添加sawitch的加速呢

### ISSUE THREAD

**Issue by YZYZYZGOD** [skydevil88/XboxDownload#24]
感谢大佬的工具，让我的xss和ps5都能满速下载了，想问下未来会不会考虑添加支持switch的加速呢

**Comment by skydevil88** [comment]
switch 早有了
使用说明里面有写，不过我没有 NS ，效果不知道。
7. Nintendo Switch
首先测速（参考 EA） 
方法一、导出规则写入路由器 Hosts。(需要路由器支持)
方法二、写入系统 Hosts 文件，然后 PC 开热点给 NS 使用。
方法三、指定 NS 下载域名 IP，点击开始监听，NS 把 DNS IP 设置为电脑 IP（本机 IP）

**Comment by YZYZYZGOD** [comment]
> 

啊啊啊，看到了，抱歉之前没注意到NS的和EA的在一起。感觉我的网络可能不是特别好，在软件上测的可以跑满的速度，NS连上之后没什么提升。很可惜NS没有国内的IP可以用。
谢谢大佬啦

**Comment by skydevil88** [comment]
刚弄了一台OLED回来，我用日本IP 23.218.94.114 在路由器看到下载速度30-50Mbps。

**Comment by YZYZYZGOD** [comment]
> 刚弄了一台OLED回来，我用日本IP 23.218.94.114 在路由器看到下载速度30-50Mbps。

谢谢大佬，我使用的是校园网，应该是所选用的IP原因，PS5和XBOX下载都能超过我所开通的30兆网络，一般能达到70-100兆网的速度，所以就想着switch能不能也有这种速度，不过switch貌似没找到有这样的IP，不过也基本能跑满速度了，非常感谢大佬
