### ISSUE TITLE
很好奇是怎么实现HTTPS劫持的

### ISSUE THREAD

**Issue by roadwide** [skydevil88/XboxDownload#25]
看了一眼代码，应该是本地开443端口自签名证书然后劫持的。但是访问的时候是怎么信任这个证书的呢？软件我也没记得提示过添加证书

**Comment by skydevil88** [comment]
你点击开始监听就把证书添加上了。

**Comment by roadwide** [comment]
> 你点击开始监听就把证书添加上了，停止监听自动移除。

我试了一下劫持其他网站，浏览器会提示不信任证书。可能EA和xbox不确认证书？

**Comment by skydevil88** [comment]
证书只添加了以下几个域名

*.akamaihd.net
*.akamaized.net
*.origin.com
*.steampowered.com
steamcommunity.com
