### ISSUE TITLE
只有nginx要怎么操作

### ISSUE THREAD

**Issue by cwdsun** [skydevil88/XboxDownload#26]
我的openwrt固件只有nginx，没有uhttp和lighttpd。
请问这种情况要做哪几个步骤？

我用的R2S，固件选择不多，只有目前这个固件能满足我其他需求，所以无法更换其他固件。

**Comment by skydevil88** [comment]
https://github.com/skydevil88/XboxDownload/blob/master/README_OpenWrt.md#%E6%96%B9%E6%B3%95%E4%BA%8Cnginx

**Comment by cwdsun** [comment]
固件自带nginx，没有uhttpd。
我需要安装uhttpd吗？
我直接创建xbox.conf后，就进不去路由器管理页面了

**Comment by skydevil88** [comment]
不需要再装uhttpd，或者你直接在nginx.conf里面添加跳转策略看看行不行。
