### ISSUE TITLE
下载速度达不到网络满速

### ISSUE THREAD

**Issue by ez-flash** [skydevil88/XboxDownload#27]
我是在PC上用，Windows 11
使用xboxdownload测速的时候，选择的节点测试文件，下载可以达到当前家宽的上限40MB/s，但是当在xbox程序里面开始下载游戏的时候，只有最高10MB/s，无法超出，当同时开启多个游戏下载的时候，例如2个游戏，则是20MB/s，3个游戏30MB/s，不知道是xbox程序还是Windows系统哪里限制了下载的速度，请问这个有解决方法吗？

**Comment by skydevil88** [comment]
你是用监听方式还是改Hosts，如果系统用了com域名下载需要用监听方式跳转到cn域名下载。

**Comment by ez-flash** [comment]
监听方式, com域名已经跳转了，无论是xboxdownload还是系统终端窗口，ping com域名，xboxdownload这里都会有DNS跳转cn的反馈

**Comment by ez-flash** [comment]
大概找到了解决方法
https://www.esportstales.com/tech-tips/how-to-fix-xbox-app-slow-download-speed-pc-game-pass

晚上回家试试
