### ISSUE TITLE
从上周开始只要改了dns就下载不成功，不知道是不是我一个有问题

### ISSUE THREAD

**Issue by JeffCheung85** [skydevil88/XboxDownload#28]
之前是在路由器挂SmartDNS修改的，用了蛮久的，最近开始下载不成功，后来排除一堆问题之后定位到是dns修改的问题，不知道为什么，也试过用pc开下载助手，只要修改dns就下载报错，错误代码是0x78e00005，把dns恢复原状就能正常下载了，但是速度很慢，应该是走com域名了，现在不知道怎么办

**Comment by skydevil88** [comment]
你是不是把cn域名ip填到com域名了？
com域名不能使用cn ip,  反过来可以。

**Comment by JeffCheung85** [comment]
address /assets1.xboxlive.com/113.106.101.129
是的，但是xbox不就是因为com域名慢所以让他映射到cn域名下嘛，那如果com域名不能使用cn的ip，那应该怎么加速

**Comment by skydevil88** [comment]
只能用下载助手或者OpenWrt做跳转。

**Comment by JeffCheung85** [comment]
> 只能用下载助手或者OpenWrt做跳转，或者你用com域名测速找一个国外IP。

懂了，openwrt怎么做跳转呀，用nginx做反代嘛，nginx不是很熟，有哪个插件简单做到的给个关键字我去学习下嘛

**Comment by skydevil88** [comment]
https://github.com/skydevil88/XboxDownload/blob/master/README_OpenWrt.md
