### ISSUE TITLE
xbox只能跑到最多20多mbps

### ISSUE THREAD

**Issue by joejph** [skydevil88/XboxDownload#3]
用工具下载测速，以及复制下载连接用其他工具下载可以跑满宽带4、500mbps，但是就是在xbox里面下载只有20mbps左右，知道是怎么回事不？谢谢。

**Comment by skydevil88** [comment]
Xbox DNS 有没有设置到 PC IP，下载助手里面有没有HTTP 301日志。

**Comment by joejph** [comment]
都设置了，也能看见日志，从路由器后台也能看见和绑定的cn 对应ip的四个连接，但就是速度上不去

**Comment by skydevil88** [comment]
换根网线试试，再不行就用PC下载。

**Comment by joejph** [comment]
用自带的edge 打开speed test都可以跑到200多兆，看来只能用pc下载了。本地上传不知道是不是设置问题还是怎么，xbox会自动停止，目前只能通过移动硬盘拷。

**Comment by skydevil88** [comment]
自动停止可能文件有损坏，你可以取消本地上传让Xbox从网上下载一部分，等过了损坏那部分再从本地上传，不然从移动硬盘拷也可能会停止。

**Comment by joejph** [comment]
找到原因了，是交换机的原因，好像就是专门针对xbox游戏下载限速，其他下载都正常。
