### ISSUE TITLE
一些关于README_OpenWrt.md的疑问

### ISSUE THREAD

**Issue by J1mmyHuang** [skydevil88/XboxDownload#31]
当我把OpenWrt路由器作为旁路由时，我在主机名中以.com结尾后面的ip地址填OpenWrt还是主路由
<img width="716" alt="Op3" src="https://user-images.githubusercontent.com/100363073/155544285-5f105713-a9d1-4da5-be89-983d9160b86d.png">

**Comment by skydevil88** [comment]
主路由
