### ISSUE TITLE
请问没有web管理界面如何更改监听端口？

### ISSUE THREAD

**Issue by Oatnait** [skydevil88/XboxDownload#32]

**Comment by skydevil88** [comment]
编辑 /etc/config/uhttpd
可以看 Lighttpd 修改方法。

**Comment by Oatnait** [comment]
好的，我按照您的方法试了一下好像不成功，com地址并未跳转，我不清楚到底是什么原因，或许跟端口转发有关？我设置了80端口的转发用于在外网访问软路由

**Comment by skydevil88** [comment]
先在内网用浏览器测试一下，个人宽带一般没有公网IP，就算有也没开放80端口。

**Comment by Oatnait** [comment]
我似乎找到了一个问题，在配置好/etc/nginx/conf.d/xbox.conf文件以后，启动nginx服务的时候报错了，请问下这个是甚么原因呢

root@OpenWrt:~# /etc/init.d/nginx start
nginx_init: NOT using conf file!
show config to be used by: nginx -T -c '/etc/nginx/uci.conf'

**Comment by skydevil88** [comment]
检查一下confg文件有没有错，实在不行可以用 Lighttpd。
