### ISSUE TITLE
旁路由怎么关闭ipv6

### ISSUE THREAD

**Issue by cwdsun** [skydevil88/XboxDownload#33]
因为有mesh的需求，只能用硬路由做主路由（开启DHCP），openwrt软路由当旁路由（关闭DHCP）。
xsx手动改ip指向旁路由。

这种情况下防火墙那段代码是不是就无效了？我一直关不掉ipv6

这种情况又该怎么关闭ipv6呢（硬路由上无法关闭ipv6）

**Comment by skydevil88** [comment]
试试代码加到旁路由或者直接在旁路由里关闭IPv6看看行不行。
