### ISSUE TITLE
为什么监听了之后什么日志都没有啊

### ISSUE THREAD

**Issue by haozx1997** [skydevil88/XboxDownload#36]
![image](https://user-images.githubusercontent.com/32725034/177827911-97180681-82b5-4e2c-81dc-dd7a2e6acdfc.png)

**Comment by skydevil88** [comment]
HTTP日志不是必需的，PC直接使用了 cn 域名下载，省去 HTTP 服务跳转这一步骤，所以就没有 HTTP 日志，加速一样有效。
另外模拟飞行这款游戏内载数据包不走微软下载域名，没法加速。
