### ISSUE TITLE
能解决xgp游戏库一直转圈无法显示的问题吗

### ISSUE THREAD

**Issue by tonycwq** [skydevil88/XboxDownload#37]
您好，请问xgp的游戏库无法显示，一直转圈。您的下载助手能解决这个问题吗？我看软件里有个域名的菜单，里面可以选阿里云什么的。不知道如何使用？ 如果能有效，是否也能通过路由器方式实现，谢谢！

**Comment by skydevil88** [comment]
昨天更新加了Akaimi CDN 优选IP功能，正好解决商图片、游戏库等加速。
