### ISSUE TITLE
电信网络，最近的网络测试只有9-10MB，是否不太正常？

### ISSUE THREAD

**Issue by netsesame2** [skydevil88/XboxDownload#38]
南京电信，
附件的几个ip测试，下载速度都在9-10MB/s 波动。
看到别人都能到好几百，是否不正常？有什么影响因素

**Comment by skydevil88** [comment]
先检查网络，测速网址 https://www.speedtest.cn/
如果你家上网带宽是100Mbps基本就是满了。

**Comment by netsesame2** [comment]
晚上回去看一下
