### ISSUE TITLE
 xvcf1.xboxlive.com之类的域名会跳转吗

### ISSUE THREAD

**Issue by OkifuZ** [skydevil88/XboxDownload#39]
多谢你的软件！
rt, 我的问题是，除了 asset1.xboxlive.com，xvcf1.xboxlive.com会跳转吗？我看了一下我下载的时候一直在访问该域名。

**Comment by skydevil88** [comment]
会跳转
包括以下com游戏下载域名
assets1.xboxlive.com
assets2.xboxlive.com
dlassets.xboxlive.com
dlassets2.xboxlive.com
d1.xboxlive.com
d2.xboxlive.com
xvcf1.xboxlive.com
xvcf2.xboxlive.com
