### ISSUE TITLE
关于openwrt版本的问题

### ISSUE THREAD

**Issue by Glenffi** [skydevil88/XboxDownload#4]
老哥我是从NGA来的，目前我发现xbox下载游戏走的ssr梯子流量，梯子我用的是绕开大陆ip的模式。
这样设置以后是否还会走梯子流量？因为我梯子是买的vps，限速30mbps的我怀疑下载速度慢很大原因是由于vps限速。
所以我想让xbox下载时不走梯子流量，后续看油管奈飞时走梯子流量。不知道这个需求按照这样设置能否满足？

另外我的openwrt的界面跟截图中区别比较大，目前看着还有点蒙=。=

**Comment by skydevil88** [comment]
跳转后就是用assets1.xboxlive.cn和国内IP下载，除非设置全局模式，否则不会走梯子流量。

openwrt在 网络->DHCP/DNS->找到自定义挟持域名这个页面就行，安装lighttpd用SSH操作。
