### ISSUE TITLE
希望可以复制多个日志

### ISSUE THREAD

**Issue by huajip** [skydevil88/XboxDownload#41]
如果可以提供日志的输出位置之类的也是可以的 主要是能方便复制多个下载链接去其他的下载工具之类的

**Comment by skydevil88** [comment]
如果需要跳转，HTTP日志成千上万，也不好复制。
现在PC商店游戏可以在游戏标签页直接获取，主机只需把cn域名指定为本机IP，回到主机商店浏览游戏详情，不需要下载就能显示下载链接。

**Comment by huajip** [comment]
我主要是希望有一个可以导出当前日志的方法 或者可以同时拖拽多个行进行复制

**Comment by skydevil88** [comment]
升级最新版本，右键增加导出全部日志选项。
