### ISSUE TITLE
微软商店应用的比价功能抛出异常

### ISSUE THREAD

**Issue by aTerminal** [skydevil88/XboxDownload#43]
实例应用：https://www.microsoft.com/store/productId/9P0PQ8B65N8X

![image](https://user-images.githubusercontent.com/47311923/190396909-350db0d8-e1eb-4c85-bd79-2fe5d7b1e6fb.png)

**这不是一个游戏**，如果微软商店应用的价格获取API与游戏不一致，实现商店应用的比价功能有难度，可以考虑将该按钮隐藏或变灰。

**Comment by skydevil88** [comment]
已修复。
