### ISSUE TITLE
N1旁路由上搭了Nginx Proxy Manager,如何设置

### ISSUE THREAD

**Issue by Java2Boy** [skydevil88/XboxDownload#44]
环境：主路由R6300v2 梅林 + 旁路由 N1 Docker（NPM） 宽带300M联通，下载速度最多90mbps

问题：是否能用Docker下直接跑配置，配合NPM进行设置？

非常感谢，主机为XSS

**Comment by skydevil88** [comment]
http服务只用来发一个301重定向把.com域名跳转到.cn域名，你用什么方法实现这个功能都可以。
下载速度跟CDN服务器有关，可以多换几个节点试试。

**Comment by Java2Boy** [comment]
换到主路由解决，旁路由没办法全类型 NAT
