### ISSUE TITLE
建议：提供一个ARM64版本的包

### ISSUE THREAD

**Issue by aTerminal** [skydevil88/XboxDownload#46]
只是一个突发奇想的建议，能否尝试使用ARM工具链编译一个ARM版本？
因为最近拿到了一台Windows on ARM的机器，目前的x64版本也可以跑，但效率应该要比原生的ARM版本来得低。如果这个想法实现起来很有难度可以无视我。。

**Comment by skydevil88** [comment]
升级V2版本了，原生支持 Arm64。
