### ISSUE TITLE
想问一下，直接把com的地址都劫持到CN的IP会怎么样呢

### ISSUE THREAD

**Issue by eightsheep67** [skydevil88/XboxDownload#5]
OPENWRT方法的逻辑应该是把com的地址重定向到192.168.1.1，然后监听com地址再重写成cn，然后再把cn的地址重定向到我们优选的IP。

那如果直接把com的地址重定向到cn的ip会怎么样呢？

不懂就问一下，大佬包涵……

**Comment by skydevil88** [comment]
cn IP 不能直接放到 com 里面用，服务器会提示 403 Forbidden 禁止访问。

**Comment by eightsheep67** [comment]
> cn IP 不能直接放到 com 里面用，服务器会提示 403 Forbidden 禁止访问。

cn地址重定向时，assets1和assets2的设定的地址不一样会不会有什么其他问题，还是可以起到备份的作用，因为我这边测定的两个电信IP速度都一样。实际使用起来提升显著！原来几乎最高10Mbps，现在大部分都可以达到180Mbp以上，但是也会有时候只有几十Kbps，持续时间不长，感觉像是在下载比较碎片文件。

**Comment by skydevil88** [comment]
可以设不一样，默认用assets1，通常有问题才会用到assets2。
