### ISSUE TITLE
很多游戏只有一个类别xbox one，是pc和主机通用文件吗？

### ISSUE THREAD

**Issue by zzzop** [skydevil88/XboxDownload#51]
如题
![Snipaste_2023-02-01_07-43-28](https://user-images.githubusercontent.com/28821632/215909163-3e474399-3662-41cc-85c2-721a31e2beec.jpg)

**Comment by skydevil88** [comment]
Xbox One 游戏可以用在XS（有的游戏只有one版本），反过来不可以，PC不能通用。 
部分游戏各机种 ProductId ID 不一样，需要分别查找。
