### ISSUE TITLE
请问下，更新2.0.0.9后，没有PS内容了？

### ISSUE THREAD

**Issue by TPluto516** [skydevil88/XboxDownload#52]

**Comment by skydevil88** [comment]
之前的测速文件太老旧了，手上也没有PS。Akamai IP也能用在PS上，或者你把PS测速文件链接用监听抓取发过来，我再加回去。

**Comment by TPluto516** [comment]
PS5-糖豆人
http://gst.prod.dl.playstation.net/gst/prod/00/PPSA04478_00/app/pkg/26/f_f2e4ff2bc3be11cb844dfe2a7ff8df357d7930152fb5984294a794823ec7472b/EP1464-PPSA04478_00-XXXXXXXXXXXXXXXX_0.pkg

PS4-生化危机7
http://gs2.ww.prod.dl.playstation.net/gs2/appkgo/prod/CUSA03962_00/4/f_526a2fab32d369a8ca6298b59686bf823fa9edfe95acb85bc140c27f810842ce/f/UP0102-CUSA03962_00-BH70000000000001_0.pkg

**Comment by skydevil88** [comment]
有测速文件吗，就是PS系统测速那个，游戏经常要更新。

**Comment by TPluto516** [comment]
应该是这个
http://gst.prod.dl.playstation.net/networktest/get_192m?p=3&title=NPXS40087

**Comment by skydevil88** [comment]
更新 v2.0.0.10

**Comment by TPluto516** [comment]
好的，感谢
