### ISSUE TITLE
M1 Macbook怎么用？

### ISSUE THREAD

**Issue by dansenxl** [skydevil88/XboxDownload#57]
M1 Macbook怎么用，没有windows

**Comment by skydevil88** [comment]
路由器刷一个OpenWrt或者安装Windows模拟器。

**Comment by dansenxl** [comment]
> 路由器刷一个OpenWrt或者安装Windows模拟器。

是openwrt，主要是怎么找到最快的IP

**Comment by skydevil88** [comment]
装一个Windows模拟器跑一下测速。
