### ISSUE TITLE
该网站https://ping.chinaz.com/ ping后复制网站内容点击提交没有反应

### ISSUE THREAD

**Issue by Monster-DP** [skydevil88/XboxDownload#58]
![image](https://user-images.githubusercontent.com/47738288/222894374-36ac1173-e7d0-4833-95f2-705215c96ab3.png)
![image](https://user-images.githubusercontent.com/47738288/222894451-43871482-1ace-4578-8b34-a188f38c8aea.png)
![image](https://user-images.githubusercontent.com/47738288/222894453-adaca709-f653-438a-bfe3-294e6a77cc78.png)
![image](https://user-images.githubusercontent.com/47738288/222894738-bdaa558d-82f2-40e0-a664-da4118e6c6ac.png)

该网站https://ping.chinaz.com/ ping后复制网站内容点击提交没有反应

**Comment by skydevil88** [comment]
我这里测试正常。

**Comment by Monster-DP** [comment]
好神奇呀 我重新下载了最新版还是不行 搞不懂😢

**Comment by skydevil88** [comment]
Ping检测，不是国内测速。

**Comment by Monster-DP** [comment]
收到 解决了
