### ISSUE TITLE
PC版微软模拟飞行的更新包无法加速

### ISSUE THREAD

**Issue by eightsheep67** [skydevil88/XboxDownload#6]
PC版的微软模拟飞行，打开以后有124G的更新包，但是下载速度奇慢，我发现只有路由器开全局梯子，速度才能上到20Mbps以上。然后我用tcpdump抓包，发现下载的地址就是asset1.xboxlive.com:7681，这个是因为cn的地址下不到所以只能从com下吗？

我出国软件是ssrplus，如过把xboxlive.com这个域名加入强制代理的话，那这个重写url和代理的先后顺序会是怎么样的呢？
会先重写成cn还是，会先被强制代理

**Comment by eightsheep67** [comment]
我实际尝试了一下，把cn加入强制不代理，com加入强制代理，貌似可以做到如果只有com地址可以下载的，就梯子加速到50Mbps左右，如果cn有的就不走梯子，几乎满速。

**Comment by skydevil88** [comment]
这个游戏更新包不走那几个Xbox游戏下载域名，没法加速。
