### ISSUE TITLE
最新版本打开工具 TAG 就卡死了

### ISSUE THREAD

**Issue by yan8950040** [skydevil88/XboxDownload#61]
最新版本打开工具 TAG 就卡死了

**Comment by yan8950040** [comment]
希望能修改一下

**Comment by skydevil88** [comment]
点开工具会调用powershell验证应用游戏安装目录，你的系统Powershell能否正常打开？

**Comment by yan8950040** [comment]
Powershell可以正常打开

**Comment by skydevil88** [comment]
最新版本屏蔽错误。

**Comment by cao888** [comment]
我也是这样，powershell能打开的，且关闭了所有杀毒软件

**Comment by skydevil88** [comment]
> 我也是这样，powershell能打开的，且关闭了所有杀毒软件

v2.0.0.30 还出错吗？

**Comment by liuchuhan1** [comment]
> > 我也是这样，powershell能打开的，且关闭了所有杀毒软件
> 
> v2.0.0.30 还出错吗？

还是出错，系统版本22623.1255

**Comment by skydevil88** [comment]
> > > 我也是这样，powershell能打开的，且关闭了所有杀毒软件
> > 
> > 
> > v2.0.0.30 还出错吗？
> 
> 还是出错，系统版本22623.1255

更新到 v2.0.0.31，再有问题只能你自己装一个Visual Studio查看原因。
