### ISSUE TITLE
r4s istoros安装lighttpd并修改文件后运行报错

### ISSUE THREAD

**Issue by Duneon** [skydevil88/XboxDownload#62]
![image](https://user-images.githubusercontent.com/56660261/230113997-354d2947-df48-47c2-be98-a88ae1eef56c.png)

### Documentation
# https://wiki.lighttpd.net/
#
### Configuration Syntax
# https://wiki.lighttpd.net/Docs_Configuration
#
### Configuration Options
# https://wiki.lighttpd.net/Docs_ConfigurationOptions
#
### Configuration Variables (potentially used in /etc/lighttpd/conf.d/*.conf)
var.log_root    = "/var/log/lighttpd/"
var.server_root = "/www/"
var.state_dir   = "/var/run/"
var.home_dir    = "/var/lib/lighttpd/"
var.conf_dir    = "/etc/lighttpd"
var.vhosts_dir  = server_root + "/vhosts"
var.cache_dir   = "/var/cache/lighttpd"
var.socket_dir  = home_dir + "/sockets"

### OpenWRT lighttpd base configuration
server.document-root        = server_root
server.upload-dirs          = ( "/tmp" )
server.errorlog             = log_root + "error.log"
server.pid-file             = state_dir + "lighttpd.pid"
server.username             = "http"
server.groupname            = "www-data"

# historical; preserved for compatibility; should have been disabled by default
index-file.names            = ( "index.php", "index.html",
                                "index.htm", "default.htm",
                              )

static-file.exclude-extensions = ( ".php", ".pl", ".fcgi" )

include "/etc/lighttpd/mime.conf"
include "/etc/lighttpd/conf.d/*.conf"

### Customizations
# customizations should generally be placed in separate files such as
#   /etc/lighttpd/conf.d/00_vars.conf    # override variables for conf.d/*.conf
#   /etc/lighttpd/conf.d/zz_custom.conf  # override other conf.d/*.conf settings
server.modules = ( "mod_redirect" )
$HTTP["host"] =~ "^(assets1|assets2|d1|d2|xvcf1|xvcf2)\.xboxlive\.com$" {
	url.redirect = ( "(.*)" => "http://assets1.xboxlive.cn$1" )
}
$HTTP["host"] =~ "^(dlassets|dlassets2)\.xboxlive\.com$" {
	url.redirect = ( "(.*)" => "http://dlassets.xboxlive.cn$1" )
}
server.modules +=( "mod_proxy")
proxy.server = ( "" => (( "host" => "127.0.0.1", "port" => 8088	)))

**Comment by skydevil88** [comment]
看描述好像是新版本Lighttpd不能直接修改系统conf， 你把代码写进 /etc/lighttpd/conf.d/00_vars.conf 试试。

**Comment by Duneon** [comment]
> 看描述好像是新版本Lighttpd不能直接修改系统conf， 你把代码写进 /etc/lighttpd/conf.d/00_vars.conf 试试。
该目录下并没有这个文件
![image](https://user-images.githubusercontent.com/56660261/230612017-fe0e3886-f671-4e7a-82cd-d0cf9644bd01.png)
xu'y需要新建一个么？

**Comment by skydevil88** [comment]
先换个Nginx用，等有空再查看这个问题。
