### ISSUE TITLE
这个软件是不是 Windows 7 的无法打开？

### ISSUE THREAD

**Issue by suifengpiaoyang** [skydevil88/XboxDownload#63]
问题事件名称:	APPCRASH
  应用程序名:	XboxDownload.exe
  应用程序版本:	2.0.0.30
  应用程序时间戳:	63ed8286
  故障模块名称:	KERNELBASE.dll
  故障模块版本:	6.1.7601.24387
  故障模块时间戳:	5c7f3ad8
  异常代码:	e0434352
  异常偏移:	000000000000be0d
  OS 版本:	6.1.7601.2.1.0.256.48
  区域设置 ID:	2052
  其他信息 1:	c489
  其他信息 2:	c489bcf93e346f7e8acd62314cba05cf
  其他信息 3:	f0b4
  其他信息 4:	f0b4fdcacbe3019440d9c2981f7f2c41

**Comment by skydevil88** [comment]
Win7可以用V1版本 https://pan.baidu.com/s/1ZqBvWjpGYZXBL8WaitMLCQ?pwd=q3cp

**Comment by suifengpiaoyang** [comment]
谢谢，可以正常打开了:relaxed:
你分享这两个软件的大小不大，或许可以放在国外云盘。百度下载还得安装云盘，真的一言难尽啊。
