### ISSUE TITLE
openwrt安装了，但是下载速度还是很慢

### ISSUE THREAD

**Issue by Zhengshihangcn** [skydevil88/XboxDownload#64]
1000兆的宽带，下载速度只有50-70mbps？

**Comment by skydevil88** [comment]
速度跟CDN有没有你下载游戏缓存有关系，可以多换几个节点IP试试，国内节点速度不行也可以换Akamai IP.

**Comment by Zhengshihangcn** [comment]
移动宽带，CDN的节点只能选移动还是可以选其他电信或者联通？

**Comment by skydevil88** [comment]
可以选其它运营商，那个快就用那个。

**Comment by Zhengshihangcn** [comment]
> 可以选其它运营商，那个快就用那个。

openmwrt可以直接通过host或者dnsmasq规则来设置吗? 域名映射一个个添加太麻烦了

**Comment by Zhengshihangcn** [comment]
> 可以选其它运营商，那个快就用那个。

openmwrt可以直接通过host或者dnsmasq规则来设置吗? 域名映射一个个添加太麻烦了,    用公司的网络进行测速,可以在家里使用吗?公司是电信网络,家里是移动的, 这样测速是否会有影响

**Comment by skydevil88** [comment]
域名可以使用其它方式设置，测速不在同一地区同一运营商肯定有影响。
