### ISSUE TITLE
本地上传文件不全或损坏的闪退

### ISSUE THREAD

**Issue by happilying** [skydevil88/XboxDownload#65]
如题，本地上传状态下如果没找到文件的话程序就会闪退，虽然重新开一下就可以了，但有时候取消下载的速度慢到不忍直视，程序也就无法打开（仍然在请求文件），虽然无伤大雅，但也劳烦能修复一下（至少别闪退）

**Comment by skydevil88** [comment]
经测试没有出现你说的问题，也没有其他人反映有这个问题，把杀毒软件关闭试试。

**Comment by happilying** [comment]
重新试了一下，目前的确没问题了，可能是个人偶发（那就没事了）或者特定条件（但我没法复现），等出问题再讨论吧。

**Comment by happilying** [comment]
定位到了，条件不是未找到文件，而是文件损坏（或不全），虽然的确无伤大雅，但还是希望写一个报错，而不是闪退（以满足服务器或软路由运行需要）。如果没法解决，也无伤大雅（几乎很难碰到）。

**Comment by skydevil88** [comment]
更新到 v2.0.0.37。

**Comment by happilying** [comment]
感谢您的更新，已经解决
