### ISSUE TITLE
能否实现非大陆IP跨区购买？

### ISSUE THREAD

**Issue by Ryanrrt** [skydevil88/XboxDownload#66]
你好，想请教一下能否通过下载助手，将商店的IP重置到大陆，来实现不在大陆也可以去非锁区区域购买。我尝试使用挟持域名，将几个payment网址重定向到大陆IP，测试连接成功，但依旧提示商店区域不符。想问下这个办法行得通吗，是我没有挟持足够多的域名吗？

**Comment by skydevil88** [comment]
跨区购买是限制你的IP，不是服务器IP, 只能通过VPN等工具改变你自己的IP.

**Comment by Ryanrrt** [comment]
明白了，感谢解答。
