### ISSUE TITLE
Node.JS 重构项目？

### ISSUE THREAD

**Issue by LBYPatrick** [skydevil88/XboxDownload#68]
哈喽

我觉得我们可以一起维护一个用Node.JS写的版本，这样就可以在windows,mac, linux, 乃至树莓派上跑全自动配置的DNS Server了

大概的思路是这样的：

--> 测速：axios + 简单的计时机制
--> 架设DNS服务器用这个插件: [dns2](https://www.npmjs.com/package/dns2)

这样一来用户就不用倒腾nginx / 路由器配置 / 专门搞台windows的电脑了

**Comment by skydevil88** [comment]
测速就没法解决跨域问题，还需要一个HTTP SERVER做重定向。

**Comment by LBYPatrick** [comment]
CORS应该是客户端行为而不是服务器在拦你，所以我们可以研究一下怎么绕过这个限制

**Comment by skydevil88** [comment]
你可以带个头开发，都是打游戏的，不要指望有多少人帮你维护。

**Comment by cikichen** [comment]
我想要Mac版本

**Comment by hez2010** [comment]
既然是 winforms，最简单的跨平台方法其实是把 UI 迁移到 Avalonia，而后面的逻辑代码全都不需要重写，直接就能接着用。
