### ISSUE TITLE
¿

### ISSUE THREAD

**Issue by RxinnotRstar** [skydevil88/XboxDownload#69]
¿

![图片](https://github.com/skydevil88/XboxDownload/assets/56676566/6a2e2f07-d733-4aa1-8b9e-578c76b06e16)

**Comment by RxinnotRstar** [comment]
> Windows Version？Language？Screen Resolution？

版本号是2.0.0.46，中文，
![图片](https://github.com/skydevil88/XboxDownload/assets/56676566/44ee8598-d1ae-4836-966a-c6d36a466237)
，就是单纯的字符错误

**Comment by skydevil88** [comment]
升级到 2.0.0.47
