### ISSUE TITLE
EA 下载加速有openwrt的方法吗？

### ISSUE THREAD

**Issue by eightsheep67** [skydevil88/XboxDownload#7]
EA 下载加速有openwrt的方法吗？把特定地址劫持到特定IP的方法？

**Comment by eightsheep67** [comment]
![无标题](https://user-images.githubusercontent.com/70835718/127744795-b88af5bb-2a3b-42bf-a01a-7538b02edf34.png)
使用软件下载提示错误

**Comment by eightsheep67** [comment]
我看这个抓包，没有域名，都是IP，查了有level3，微软云之类的IP

**Comment by skydevil88** [comment]
EA Desktop 如果不能正常监听，可以点击左上角功能菜单 帮助-应用程序恢复-清理缓存。

**Comment by eightsheep67** [comment]
哦天那清理了缓存，下了50%的进度都没了……然后再尝试监听后下载，不会出错了，但是下载速度还是只有不到5MB/s左右，和没监听时候一样，指定了akamai的IP也没有效果，是因为没有使用Akamai的CDN吗？怎么才能更改成使用CDN呢？

**Comment by skydevil88** [comment]
看到下载地址用这个域名 origin-a.akamaihd.net 就是了, 我用日本 23.206.250.98 这个IP速度500M带宽满速，你可以复制下载地址用PC工具下载。

**Comment by skydevil88** [comment]
不清理缓存重启 EABackgroundService 这个服务也可以。

**Comment by skydevil88** [comment]
增加一个修复EA Desktop选项，有问题可以点击修复。

**Comment by skydevil88** [comment]
增加写入系统Hosts文件功能（测速右键选择），可以不用启动下载助手监听，直接加速。

**Comment by eightsheep67** [comment]
有效果，可以正常监听了，openwrt指定 origin-a.akamaihd.net的IP也有效了，我换了香港的地址，没能满速但是也有100Mbps以上了。
