### ISSUE TITLE
用的OpenClash，怎么才能防止走代理？部分游戏无法下载

### ISSUE THREAD

**Issue by Venompool888** [skydevil88/XboxDownload#71]
![image](https://github.com/skydevil88/XboxDownload/assets/94547252/0dd8395d-39bc-4d67-820b-ab571417c793)
根据提供的方法再将以下域名添加到规则里走直连后的确可以成功直连下载。
> - DOMAIN-SUFFIX,xvcf1.xboxlive.com,DIRECT
> - DOMAIN-SUFFIX,xvcf2.xboxlive.com,DIRECT
> - DOMAIN-SUFFIX,assets1.xboxlive.com,DIRECT
> - DOMAIN-SUFFIX,assets2.xboxlive.com,DIRECT
> - DOMAIN-SUFFIX,d1.xboxlive.com,DIRECT
> - DOMAIN-SUFFIX,d2.xboxlive.com,DIRECT
> - DOMAIN-SUFFIX,dlassets.xboxlive.com,DIRECT
> - DOMAIN-SUFFIX,dlassets2.xboxlive.com,DIRECT
> - DOMAIN-SUFFIX,dl.delivery.mp.microsoft.com,DIRECT
> - DOMAIN-SUFFIX,tlu.dl.delivery.mp.microsoft.com,DIRECT
但是在下载*地平线4*的时候发现走的是tlu.dl.delivery.mp.microsoft.com会出现下载速度为0的情况

**Comment by Venompool888** [comment]
![image](https://github.com/skydevil88/XboxDownload/assets/94547252/104804d8-a123-40ed-be15-221a98599e5e)  
下载地平线的时候会碰到这域名，但是根据chatgpt的回答貌似是广告。。  
![image](https://github.com/skydevil88/XboxDownload/assets/94547252/8e85f4c8-1a98-4447-b468-a478b10af7ba)

**Comment by Venompool888** [comment]
发现依旧部分游戏下载走的是海外ip导致出现消耗代理流量的情况

**Comment by skydevil88** [comment]
部分PC游戏下载(地平线4、盗贼之海等)会使用 tlu.dl.delivery.mp.microsoft.com，这个域名国内经常出问题，可以试试用 Akamai IP.
规则 DOMAIN-SUFFIX 是泛域名解析，上面几个下载域名用 DOMAIN 就可以。

**Comment by skydevil88** [comment]
下载速度还要看CDN服务器有没有这个游戏缓存，部分游戏无法下载可以在商店页面找到链接用FDM等软件下，又快又稳。

**Comment by Venompool888** [comment]
> 下载速度还要看CDN服务器有没有这个游戏缓存，部分游戏无法下载可以在商店页面找到链接用FDM等软件下，又快又稳。

链接要在哪里可以搞到哇，有对应工具么

**Comment by skydevil88** [comment]
https://xbox.skydevil.xyz/
