### ISSUE TITLE
支持捆绑包一键下载

### ISSUE THREAD

**Issue by cikichen** [skydevil88/XboxDownload#72]
捆绑包会有多个下载地址，现在只能一个一个的选择很麻烦，希望支持一键下载
<img width="951" alt="image" src="https://github.com/skydevil88/XboxDownload/assets/1478821/365c2e21-e1f9-48c3-b0d7-5ed2b0607efa">

**Comment by skydevil88** [comment]
下载文件包含三种平台，一键下载不现实。

**Comment by cikichen** [comment]
> 下载文件包含三种平台，一键下载不现实。

@skydevil88 多选呢？

**Comment by skydevil88** [comment]
没必要，像真人快打这个游戏有52个包，很多都是10M左右的引导文件，真正要用的没几个。
