### ISSUE TITLE
添加拳头游戏cdn

### ISSUE THREAD

**Issue by auqhjjqdo** [skydevil88/XboxDownload#74]
拳头客户端下载瓦罗兰特速度太慢了，能否添加拳头游戏cdn的代理

**Comment by skydevil88** [comment]
没有玩过这个，你用Fiddler抓包看看下载域名用的是不是Akamai CDN，如果不是那就没办法，是的话就在测速找个一个快的Akamai IP，写进Hosts文件。

**Comment by skydevil88** [comment]
在CDN页面增加一条记录，服务勾选设置本机DNS。
*.secure.dyn.riotcdn.net

<img width="724" alt="a" src="https://github.com/skydevil88/XboxDownload/assets/60030602/fccb169f-a931-4f65-8918-ea62b27e12a1">

**Comment by auqhjjqdo** [comment]
拳头客户端不走系统代理，不能用fiddler抓包，我试了下这个域名的确是akamai的cdn，加速有效果，感谢

**Comment by skydevil88** [comment]
域名可以改为 *.dyn.riotcdn.net
