### ISSUE TITLE
加速无效

### ISSUE THREAD

**Issue by jay52121** [skydevil88/XboxDownload#75]
1.全球最大游戏-微软模拟飞行2020,以前更新加速是有效的,现在无效了,如何定位问题?
2.在线地图请教下有没有办法加速呢?

**Comment by jay52121** [comment]
up:搞错了,是游戏内的更新.请问有没有办法加速呢?路由器数据:
flightsimulator.azureedge.net:443   13.107.246.73

**Comment by skydevil88** [comment]
不支持，用的是微软自家服务器，没有CDN。
以前主机版本数据打包成一个安装包，现在分开了。
