### ISSUE TITLE
无法转换PC模式

### ISSUE THREAD

**Issue by cikichen** [skydevil88/XboxDownload#77]
win11系统，amd平台，关闭了360和微软管家，点击转换PC模式没有任何反应

https://github.com/skydevil88/XboxDownload/assets/1478821/fe90ae3c-e4de-4f90-8cd0-759501f76d01

**Comment by skydevil88** [comment]
不清楚什么原因被系统阻止写入硬盘MBR，可以用 DiskGenius 手动修改。
https://github.com/skydevil88/XboxDownload/issues/17
