### ISSUE TITLE
updata.xboxlive.com

### ISSUE THREAD

**Issue by ailinician** [skydevil88/XboxDownload#78]
大佬，xbox里面游戏更新的速度感觉比较慢，游戏更新是使用到这个域名，是否可以增加这个域名的重定向，提升游戏更新的速度呢

**Comment by skydevil88** [comment]
下载更新域名是用同一个，Xbox使用增量更新，安装包也是同一个，自动选择下载其中一部分更新文件。
主机游戏使用cn1、cn2域名，PC游戏使用cn1、应用下载域名，你可以在商店选项卡搜索下载游戏链接，看看使用那个域名。
模拟飞行游戏内下载这种没法加速。
