### ISSUE TITLE
使用软路由URL重写跳转的方式后，XBOX会员福利打不开

### ISSUE THREAD

**Issue by JinjerTK** [skydevil88/XboxDownload#79]
如题，应该是把com跳转为cn导致打不开Xbox里XGP的会员福利页面，但用路由改Hosts的方式又跑不满下载游戏时的网速。本人小白，不知道描述得是否清楚，看看大佬有没有好的解决方法，比如固定会员福利页面不加速？辛苦了

**Comment by skydevil88** [comment]
只跳转下载域名，会员福利页面打不开是其它原因.

**Comment by JinjerTK** [comment]
但是测试后发现没跳转之前是正常的，跳转之后才打不开的

**Comment by skydevil88** [comment]
我这里打开正常，微软服务器在国内就是这样，经常被干扰，时好时环。

**Comment by JinjerTK** [comment]
好的，我再试试，谢谢大佬
