### ISSUE TITLE
openwrt方法能否同时加速XBOX国内和国际域名？

### ISSUE THREAD

**Issue by eightsheep67** [skydevil88/XboxDownload#8]
是否有办法同时加速国际国内域名
或者是问，微软商店或者XBOX在下载的时候，是怎么判断使用CN还是使用COM，这个是有规律的还是他默认就是走COM所以我们才需要重定向到CN？
如果微软自己有走COM或者CN的规则的话，是否可以直接在主机名里把COM和CN分别对应到测速最快的IP。

**Comment by skydevil88** [comment]
OpenWrt 安装 Lighttpd，https://github.com/skydevil88/XboxDownload/blob/master/README_OpenWrt.md

Xbox和微软商店者是根据使用者 IP 分配下载域名，国内 IP 就用 cn , 用了加速器或者科学上网就会变 com.

**Comment by eightsheep67** [comment]
那我不用lighttpd来重定向com到cn，直接在主机名里把com和cn的多个地址定向到测速最快的IP能达到cn和com同时加速的效果吗？

**Comment by skydevil88** [comment]
可以，只要com下载速度快就没问题。

**Comment by eightsheep67** [comment]
> 可以，只要com下载速度快就没问题。
> cdn没有缓存会自动回源，只是速度变慢，不会没资源。

意思是，只要是国内IP访问（不要科学或者另外加速器导致IP变成国外的），微软就会分配国内cn域名来下载，然后即便是cn域名没有对应的缓存，也不会切回com下载。
那用lighttpd重定向这一步的作用是什么呢……是为了使用加速器联网游戏的用户吗？
一般正常用户没有联网游戏需求的其实不需要重定向这一步骤是吧？

**Comment by skydevil88** [comment]
完全不用加速器或者科学上网可以不使用重定向, 但是用了变com会在一段时间都是用com, 不管你是否用cn IP.

**Comment by eightsheep67** [comment]
> 完全不用加速器或者科学上网可以不使用重定向, 但是用了变com会在一段时间都是用com, 不管你是否用cn IP.

明白了！！！那我就com和cn都指定一个测速最快IP即可。谢谢大佬解答！
