### ISSUE TITLE
请教一下，nginx的配置是不是写错了？

### ISSUE THREAD

**Issue by mypierce** [skydevil88/XboxDownload#84]
nginx的配置文件如下

server_names_hash_bucket_size 64;
server {
        listen 80;
        server_name assets1.xboxlive.com assets2.xboxlive.com d1.xboxlive.com d2.xboxlive.com xvcf1.xboxlive.com xvcf2.xboxlive.com dlassets.xboxlive.com dlassets2.xboxlive.com;
        if ($host !~* "^dlassets2?\.xboxlive\.com$") {
                return 301 http://assets1.xboxlive.cn$request_uri;
        }
        if ($host ~* "^dlassets2?\.xboxlive\.com$") {
                return 301 http://dlassets.xboxlive.cn$request_uri;
        }
}

看起来没有把assets1、assets2、d1、d2、xvcf1、xvcf2转发到assets1.xboxlive.cn，lighttpd和caddy都有类似的配置

是否需要对上面的代码进行修改？

**Comment by skydevil88** [comment]
没有错，正则表达式。
