### ISSUE TITLE
本地上传速度并不快

### ISSUE THREAD

**Issue by zycboss** [skydevil88/XboxDownload#87]
![image](https://github.com/skydevil88/XboxDownload/assets/29044143/e43350f1-2410-4802-b6fb-1258a7b7b8d9)
已经用迅雷下载好离线游戏文件了，但是开启本地上传监听以后，最快速度也只有10+M/S，并不比直接下载快多少
而且大部分时候，本地上传速度只有5M/S左右，我这是试了很多次，不知道为啥突然日志里不停的刷新这个请求内容，速度才比较快
正常时候，都是只有一条日志，然后速度依旧很慢

直接监听下载的时候也是，大部分时候下载只有一条日志，速度也就7-8M/S左右，但是偶尔会疯狂刷新请求条目数的时候，速度就很快，大概能到20-30M/S
似乎是什么操作触发了多线程下载？但是我找不到什么复现的方式

**Comment by skydevil88** [comment]
PC直接安装，用工具选项卡里面的“本地安装微软商店应用软件”，为什么要用本地上传？

**Comment by zycboss** [comment]
> PC直接安装，用工具选项卡里面的“本地安装微软商店应用软件”，为什么要用本地上传？

了解了，还是这种方式最快
如果直接监听下载，即使选定了速度快的ip，实际下载速度似乎也并没有什么提升，不知道是什么原因
