### ISSUE TITLE
Win 10 XBOX DLC 无法识别

### ISSUE THREAD

**Issue by John4d3** [skydevil88/XboxDownload#88]
昨晚用下载助手下载了FH5本体和2个DLC，手动安装成功之后进游戏发现没有DLC内容，商店却显示已安装。求解，谢谢。

**Comment by skydevil88** [comment]
DLC要另外购买，如果买过了可能是网络抽风。

**Comment by John4d3** [comment]
> DLC要另外购买，如果买过了可能是网络抽风。

DLC是已拥有的，和本体一样从下载助手下载安装，但无法被本体识别。今天重新在商店下载安装就能识别到DLC了。
