### ISSUE TITLE
Some DLCs are missing download links

### ISSUE THREAD

**Issue by takutkad** [skydevil88/XboxDownload#91]
Trying productIds of some DLCs in store doesn't have any result, for example
PAYDAY 3: Syntax Error Heist: https://www.microsoft.com/store/productId/9P91FKV1L2F7 (Doesn't have Windows PC download link)
Hell's Rangers Content Pack: https://www.microsoft.com/store/productId/9NL5LK2TC9XR (No download links for any platform)
DEATHLOOP Deluxe Pack: https://www.microsoft.com/store/productId/9PF02ZFH0Z45 (No result at all)

**Comment by skydevil88** [comment]
You can download the APP and follow the prompts to update authorization to obtain all PC Xbox and XboxOne download links. Xbox Series can be obtained with LISTEN method (this method is worked on PC Xbox, Series, and XboxOne).
Some DLC does not require downloading any files (DEATHLOOP Deluxe Pack).
The app has an English version https://github.com/skydevil88/XboxDownload-EN

**Comment by takutkad** [comment]
Thanks for your response really appreciated.
PAYDAY 3: Syntax Error and Hell's Rangers Content Pack seem to have download links now in the website.

I'm using the English version of XboxDownload. When I get invalid result, the following prompt shows up
```
Authorization expired. 
1.Back to Service tab Click "Enable HTTP(S) service" and "Speed up MS Store (PC)" then press "Start" button. 
2.Open Xbox app, select a game and click install, await the log show out download link then complete update authorization.
```

I am following the instructions, I enabled `Enable HTTP(S) service` and `Speed up MS Store (PC)` and pressed `Start`. I downloaded a random game on Xbox app and the download link appeared in the log, what should I do next to complete the authorization?
I pressed `Stop` and tried again with productIds but keeps showing the same results, it sames to me by debugging through source code that XboxDownload fetches the data from https://xbox.skydevil.xyz so not sure if authorization can do any difference here.

**Comment by skydevil88** [comment]
This is an English version bug, which has been fixed now. When the log shows: Download link, means authorization has been completed.
The download link will obtain from https://xbox.skydevil.xyz first . If there is no data, use the authorization method.

**Comment by takutkad** [comment]
Thank you for fixing the bug quickly, I can confirm the app fetches download links after updating the authorization.

I wonder if there's an option to make XboxDownload to fetch data from microsoft servers first instead of https://xbox.skydevil.xyz because as far as I can see for this DLC https://www.microsoft.com/store/productId/9P2BG00QX0WT the actual latest version for Windows is `1.0.1780.0` but XboxDownload shows older version `1.0.1080.0`

**Comment by skydevil88** [comment]
When a new version is detected, it will update automatically.

**Comment by takutkad** [comment]
Seems right, I think it was my fault. I will close this issue since it's resolved.
Thanks for being responsive and helpful.
