### ISSUE TITLE
使用hyper-v新建过外部虚拟交换机的会使xbox下载助手闪退，大家注意了

### ISSUE THREAD

**Issue by lssdo12** [skydevil88/XboxDownload#92]
具体表现为 "服务"选项卡的本机ip不显示，且本机ip的列表为空没有选项。点击开始监听时 xbox下载助手 闪退。
在移除 hyper-v 新建的外部虚拟交换机后恢复正常

**Comment by skydevil88** [comment]
虚拟系统里面没有网卡？

**Comment by lssdo12** [comment]
> 虚拟系统里面没有网卡？

我是在宿主机上运行软件会闪退，虚拟机之前是用的新建外部虚拟交换机，现在把该交换机移除，使用hyper-v默认的交换机，软件恢复正常。交换机的网卡一直是选的宿主机的有线网卡

**Comment by skydevil88** [comment]
软件没有找到实体网卡，下次更新把虚拟网卡加上。
