### ISSUE TITLE
xbox与pc xbox无法正常加速

### ISSUE THREAD

**Issue by asd519020** [skydevil88/XboxDownload#94]
每次获取日志，地址都是assets2而不是assets1，导致无法正常加速下载，请问大佬如何解决？

**Comment by skydevil88** [comment]
地址1、2都是一样的，今天国内cdn好像有问题，很多人下载失败，可以勾选＂自动优选 Akamai IP ＂使用国外CDN。

**Comment by skydevil88** [comment]
这两天安装停止问题还需要在域名添加一条解释记录。
52.179.4.171 packages.xboxlive.com
