### ISSUE TITLE
测速后写入系统hosts文件, 原hosts被覆盖

### ISSUE THREAD

**Issue by MQPearth** [skydevil88/XboxDownload#95]
版本 https://github.com/skydevil88/XboxDownload/releases/tag/v2.0.1.68

**Comment by skydevil88** [comment]
写入Hosts肯定是要覆盖，Hosts文件里的规则每个域名只能写入一个IP，排前面的优先。

**Comment by MQPearth** [comment]
我的hosts文件原来有内容的, 用了这个功能后, 原来的规则全都消失了😂, 新hosts文件只有XboxDownload相关的规则了

**Comment by skydevil88** [comment]
你是点了“清除系统Hosts文件”，写入只会覆盖域名，不会清除其它规则。

**Comment by MQPearth** [comment]
嗯嗯估计是我点快了, 试了几下没复现了
