### ISSUE TITLE
有时xbox的“完整库”刷新刷不出来有什么办法呢

### ISSUE THREAD

**Issue by ailinician** [skydevil88/XboxDownload#97]
日志里没能看到哪个域名无法访问

**Comment by skydevil88** [comment]
如果只是DNS解释IP问题可以试试用加密DNS，选一个国外DoH服务器。

catalog.gamepass.com	#XGP游戏库
displaycatalog.mp.microsoft.com	微软商店通信  https://github.com/skydevil88/XboxDownload/discussions/96#discussioncomment-9784721

**Comment by ailinician** [comment]
> 如果只是DNS解释IP问题可以试试用加密DNS，选一个国外DoH服务器。 域名被墙等其它问题只能用加速器、代理解决。
> 
> catalog.gamepass.com #XGP游戏库 displaycatalog.mp.microsoft.com 微软商店通信 [#96 （评论）](https://github.com/skydevil88/XboxDownload/discussions/96#discussioncomment-9784721)

感谢您的耐心解决
待会儿试一试

**Comment by ailinician** [comment]
这两天内容库和商店都不好用，测试之后发现加上这个域名之后解决了：silver.xboxservices.com，网上说可能和Xbox商店有关系

**Comment by skydevil88** [comment]
这个域名确实跟主机商店有关系，PC好象没用到。
